# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
